WDDN_DotNetCore_Project_CE126_CE147_CE154/Classroom/Classroom/Controllers/ManageClassesController.cs
using Classroom.Models;
using Classroom.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Web.Helpers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace Classroom.Controllers
{
    public class ManageClassesController : Controller
    {
        private readonly IClassRepository _classRepository;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
        public Class[] classes { get; set; }
        public string ClassCode = "_class_code";
        public string[] teachers_list { get; set; }
        public string[] students_list { get; set; }

        public ManageClassesController(IClassRepository classRepository, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            _classRepository = classRepository;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [Route("Stream")]
        public async Task<IActionResult> Stream(int? class_code)
        {
            if(class_code != null)
                HttpContext.Session.SetInt32(ClassCode, (int)class_code);
            else
                class_code = HttpContext.Session.GetInt32(ClassCode).Value;
            var current_user = await userManager.GetUserAsync(User);
            ViewBag.isTeacher = _classRepository.isTeacher(current_user.Email, (int)class_code);

            TeacherMaterialViewModel model = new TeacherMaterialViewModel();
            Teacher[] teacher = _classRepository.GetTeacher((int)class_code).ToArray();
            model.teacher_name = teacher[0].FName + " " + teacher[0].LName;
            model.Materials = _classRepository.GetMaterials((int)class_code);
            return View(model);
        }
        [Route("People")]
        public async Task<IActionResult> People()
        {
            int class_code = HttpContext.Session.GetInt32(ClassCode).Value;
            var current_user = await userManager.GetUserAsync(User);
            ViewBag.isTeacher = _classRepository.isTeacher(current_user.Email, class_code);
            StudentTeacherViewModel mymodel = new StudentTeacherViewModel();
            mymodel.Teachers = _classRepository.GetTeacher(class_code);
            mymodel.Students = _classRepository.GetStudent(class_code);
            return View(mymodel);
        }
        [Route("AddMaterial")]
        [HttpGet]
        public IActionResult AddMaterial()
        {
            return View();
        }
        [Route("AddMaterial")]
        [HttpPost]
        public IActionResult AddMaterial(IFormFile file, Material model)
        {
            Material material = new Material();
            if (file != null)
            {
                var fileName = Path.GetFileName(file.FileName);
                var fileExtension = Path.GetExtension(fileName);
                var newFileName = String.Concat(Convert.ToString(Guid.NewGuid()), fileExtension);
                material.DocName = newFileName;
                material.DocType = fileExtension;
                using (var target = new MemoryStream())
                {
                    file.CopyTo(target);
                    material.Document = target.ToArray();
                }
            }
            material.ClassCode = HttpContext.Session.GetInt32(ClassCode).Value;
            material.Title = model.Title;
            material.Desc = model.Desc;
            material.UploadTime = DateTime.Now.Date;
            if (model.IsAssignment)
            {
                material.IsAssignment = true;
                if (model.Deadline != null)
                {
                    material.Deadline = model.Deadline;
                }
            }
            else
                material.IsAssignment = false;
            _classRepository.AddMaterial(material);
            ViewBag.isTeacher = true;
            TeacherMaterialViewModel viewModel = new TeacherMaterialViewModel();
            Teacher[] teacher = _classRepository.GetTeacher(material.ClassCode).ToArray();
            viewModel.teacher_name = teacher[0].FName + " " + teacher[0].LName;
            viewModel.Materials = _classRepository.GetMaterials(material.ClassCode);
            return View("Stream",viewModel);
        }
    }
}

WDDN_DotNetCore_Project_CE126_CE147_CE154/Classroom/Classroom/Views/Shared/_HomeNav.cshtml
<!DOCTYPE html>

<html>
<head>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Classroom</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index" Style="text-decoration: none">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="CreateClass" Style="text-decoration: none">Create-Class</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="JoinClass" Style="text-decoration: none">Join-Class</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Account" asp-action="Logout" Style="text-decoration: none">Sign-out</a>
                            @*<form asp-controller="Account" asp-action="Logout" method="post">
                                <button type="submit">Logout</button>
                            </form>*@
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        @RenderBody()
    </div>
</body>
</html>

WDDN_DotNetCore_Project_CE126_CE147_CE154/Classroom/Classroom/Views/Shared/_StudentNav.cshtml
<!DOCTYPE html>

<html>
<head>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Classroom</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index" Style="text-decoration: none">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="ManageClasses" asp-action="Stream" Style="text-decoration: none">Stream</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="ManageClasses" asp-action="People" Style="text-decoration: none">People</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        @RenderBody()
    </div>
</body>
</html>

WDDN_DotNetCore_Project_CE126_CE147_CE154/Classroom/Classroom/Views/Shared/_TeacherNav.cshtml
<!DOCTYPE html>

<html>
<head>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Classroom</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index" Style="text-decoration: none">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="ManageClasses" asp-action="Stream" Style="text-decoration: none">Stream</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="ManageClasses" asp-action="People" asp-route-class_code="" Style="text-decoration: none">People</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="ManageClasses" asp-action="AddMaterial" Style="text-decoration: none">Add Material</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="ManageClasses" asp-action="ViewSubmission" Style="text-decoration: none">View Submission</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        @RenderBody()
    </div>
</body>
</html>